# Generated by Django 2.1.15 on 2021-04-22 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='/media/defaultpp.jpg', upload_to='profiles')),
                ('age', models.IntegerField(blank=True, max_length=50)),
                ('bio', models.TextField()),
                ('parties_att_nb', models.IntegerField(default=0)),
                ('parties_org_nb', models.IntegerField(default=0)),
                ('is_organizer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
