# Generated by Django 2.1.15 on 2021-04-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210426_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profiles/defaultpp.jpg', upload_to='profiles/'),
        ),
    ]
