# Generated by Django 2.1.15 on 2021-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.ImageField(default='/media/default.jpg', upload_to='events'),
        ),
    ]
