# Generated by Django 2.1.15 on 2021-04-24 22:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20210422_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='participationlist',
            name='event',
            field=models.ForeignKey(on_delete='CASCADE', related_name='list_event', to='events.Event'),
        ),
        migrations.AddField(
            model_name='participationlist',
            name='member',
            field=models.ForeignKey(on_delete='CASCADE', related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
