# Generated by Django 5.1.4 on 2024-12-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_participation"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="TATA",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
