# Generated by Django 5.1.4 on 2024-12-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_participation_event_alter_participation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
