# Generated by Django 5.1.4 on 2024-12-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_organizer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                default="event_images/default-rafiki.jpg",
                null=True,
                upload_to="event_images/",
            ),
        ),
    ]
