# Generated by Django 5.1.4 on 2024-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="message",
            field=models.TextField(
                blank=True, help_text="Message à l'organisateur", null=True
            ),
        ),
    ]
