# Generated by Django 5.1.4 on 2025-01-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0011_participation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Prix en euros", max_digits=8
            ),
        ),
    ]
