# Generated by Django 5.1.4 on 2025-01-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_event_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="stripe_payment_intent",
            field=models.CharField(
                blank=True,
                help_text="ID de Stripe PaymentIntent",
                max_length=255,
                null=True,
            ),
        ),
    ]
