# Generated by Django 5.1.4 on 2025-01-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="consent_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
