# Generated by Django 5.1.4 on 2025-01-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_userprofile_consent_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_certified",
            field=models.BooleanField(default=False),
        ),
    ]
