# Generated by Django 5.1.4 on 2025-01-12 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_userprofile_is_certified"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="activity_type",
            field=models.CharField(default="Sortie", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="contact",
            field=models.TextField(default="Me contacter au 06 49 49 14 49"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(
                default="20:00",
                help_text="Veuillez entrer l'heure au format HH:MM.",
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'heure doit être au format HH:MM (24 heures).",
                        regex="^([01]\\d|2[0-3]):([0-5]\\d)$",
                    )
                ],
                verbose_name="Heure",
            ),
            preserve_default=False,
        ),
    ]
