# Generated by Django 5.1.4 on 2025-01-12 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_event_activity_type_event_contact_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.CharField(
                help_text="Veuillez entrer l'heure au format HH:MM.",
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="L'heure doit être au format HH:MM (24 heures).",
                        regex="^([01]\\d|2[0-3]):([0-5]\\d)$",
                    )
                ],
            ),
        ),
    ]
