# Generated by Django 5.1.4 on 2025-01-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_alter_event_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="centers_of_interest",
            field=models.TextField(
                blank=True, help_text="Qu'appréciez-vous ?", null=True
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(default="Toulouse", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(default="France", max_length=100),
            preserve_default=False,
        ),
    ]
