# Generated by Django 5.1.4 on 2025-03-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_userprofile_centers_of_interest_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="accepted",
                max_length=10,
            ),
        ),
    ]
