# Generated by Django 5.1.4 on 2025-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_alter_participation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activity_preferences",
            field=models.TextField(
                blank=True,
                help_text="Games, sports, food tours, chill drinks?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="dietary_restrictions",
            field=models.TextField(
                blank=True,
                help_text="Anything we should know if food is involved?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="event_expectations",
            field=models.TextField(
                blank=True,
                help_text="What do you hope to get from Zanmi events?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="group_size_preference",
            field=models.CharField(
                blank=True,
                help_text="Small, medium, doesn’t matter?",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="languages_spoken",
            field=models.TextField(
                blank=True, help_text="Languages you speak.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="centers_of_interest",
            field=models.TextField(
                blank=True, help_text="Things you're passionate about.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                help_text="Current city where you live.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(help_text="Country you come from.", max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short personal introduction.", null=True
            ),
        ),
    ]
